### ISSUE TITLE
About DeepNeuralNet-QSAR

### ISSUE THREAD

**Issue by Bigrock-dd** [Merck/DeepNeuralNet-QSAR#1]
Saving the trained Neural Net to models/multi_sparse_1/DeepNeuralNetParameters.npz
Traceback (most recent call last):
  File "DeepNeuralNetTrain.py", line 555, in <module>
    main()
  File "DeepNeuralNetTrain.py", line 534, in main
    num.savez(saveModelPath, **NNParametersDict);
  File "/root/miniconda3/envs/my-env/lib/python2.7/site-packages/numpy/lib/npyio.py", line 595, in savez
    _savez(file, args, kwds, False)
  File "/root/miniconda3/envs/my-env/lib/python2.7/site-packages/numpy/lib/npyio.py", line 714, in _savez
    format.write_array(fid, np.asanyarray(val),
  File "/root/miniconda3/envs/my-env/lib/python2.7/site-packages/numpy/core/numeric.py", line 544, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/root/DeepNeuralNet-QSAR-master/gnumpy.py", line 1059, in __iter__
    for i in tuple(xrange(len(self))): yield self[i]
  File "/root/DeepNeuralNet-QSAR-master/gnumpy.py", line 1026, in __getitem__
    ret = self[selectors[:axisI] + (_short_slice(_read_single_index(axisSelector, axisLen)),)]  .reshape(_deleteT2(self.shape, axisI))
  File "/root/DeepNeuralNet-QSAR-master/gnumpy.py", line 1045, in __getitem__
    if axisI==0: return garray(_cm_row_slice_read(self._base_shaped(1), sFrom, sTo), retShape, self) # slice on axis 0 is free, using _cm_row_slice_read
  File "/root/DeepNeuralNet-QSAR-master/gnumpy.py", line 587, in _base_shaped
    def _base_shaped(self, nDimsAsRows): return _cm_reshape(self._base, (_prodT(self.shape[:nDimsAsRows]), _prodT(self.shape[nDimsAsRows:])))
  File "/root/DeepNeuralNet-QSAR-master/gnumpy.py", line 165, in _cm_reshape
    else: return cm.reshape(tuple(reversed(newShape)))
  File "/root/DeepNeuralNet-QSAR-master/npmat.py", line 99, in reshape
    self.numpy_array.resize(*shape)
ValueError: resize only works on single-segment arrays
-------------------------------------------------------------------------------
I have this problem during the training of the model, how can I solve it? 
I would appreciate if  you can reply！

**Comment by xuyuting** [comment]
I hope you could include more details: Were you training the model using the example dataset or your own dataset? Which version of numpy?
